# LISTAS PART-2

# LISTAS DENTRO DE LISTAS
"""
PESSOA = [JOAO, 31]
PESSOAS.APPEND(PESSOA)>>
PESSOAS = [ [JOAO, 31], [MARIA, 23], [PEDRO, 13] ]

PRINT(PESSOAS[0][0]) == JOAO
PRINT(PESSOAS[1][1]) == 19
"""
